/* TAXA-check content.js: LoRN display + optional highlighter-green mode.
 * Replace extension/content.js with this file.
 * Requires the existing manifest permission: "storage".
 */
(()=>{'use strict';
const STORAGE_KEY='taxacheckHighlightAllLoRN';
const BLOCKED=new Set(['species','sp','spp','genus','genera','family','families','order','class','phylum','domain','bacterium','bacteria','archaeon','archaea','organism','microorganism','microbe','strain','isolate','uncultured','unclassified','unknown','candidate','candidatus']);
const COMMON_FIRST_WORDS=new Set([
'a','an','the','and','or','but','nor','so','yet',
'as','at','by','for','from','in','into','of','on','onto','to','upon','via','with','without',
'after','before','between','during','following','through','throughout','under','until','within','across','against','along','among','around','behind','below','beneath','beside','beyond','near','over','past','toward','towards',
'this','that','these','those','there','here','then','than','when','where','while','which','what','who','whom','whose','why','how',
'all','another','any','both','each','either','enough','every','few','fewer','least','less','many','more','most','much','neither','no','none','other','others','several','some','such',
'also','although','because','however','if','otherwise','since','therefore','though','thus','unless','whereas','whether',
'its','our','their','your','his','her','my','not','only','same','different','new','old','first','second','third','last','next','previous','current',
'minimum','maximum','mean','median','average','total','relative','absolute','general','overall','additional','individual','significant','significantly'
]);
function commonFirstWord(value){return COMMON_FIRST_WORDS.has(String(value||'').trim().replace(/^[\"“”'‘’]+|[\"“”'‘’,;:.!?]+$/g,'').toLowerCase());}
const MONO_RANKS=new Set(['domain','realm','kingdom','subkingdom','phylum','subphylum','class','subclass','order','suborder','family','subfamily','tribe','subtribe','genus','subgenus']);
const SKIP='script,style,noscript,textarea,input,select,option,code,pre,svg,canvas,[contenteditable=true],.tc-hit,#tc-tip';
const FULL=/\b([A-Z][a-z-]{2,})\s+([a-z][a-z-]{1,})\b/g;
const ABBR=/\b([A-Z])\.\s*([a-z][a-z-]{1,})\b/g;
const MONO=/\b[A-Z][A-Za-z-]{2,}\b/g;
const LORN_STATUS=/(?:taxonomic(?:ally)?\s+suspend(?:ed|sion)|not\s+recommended\s+for\s+(?:human\s+or\s+veterinary\s+)?medical\s+use|recommended\s+for\s+(?:human\s+or\s+veterinary\s+)?medical\s+use|\bLoRN\b)/i;
const LORN_DISPLACED=/(?:taxonomic(?:ally)?\s+suspend(?:ed|sion)|not\s+recommended\s+for\s+(?:human\s+or\s+veterinary\s+)?medical\s+use)/i;
let names,epithets,tip,lornGreen=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function installStyles(){if(document.getElementById('tc-lorn-runtime-style'))return;const style=document.createElement('style');style.id='tc-lorn-runtime-style';style.textContent=`.tc-lorn-green{color:#173600!important;background:#9cff57!important;box-shadow:inset 0 -1px 0 rgba(23,54,0,.22)!important}.tc-lorn-banner{margin:4px 0 11px;padding:10px 12px;border-left:4px solid #60b52a;border-radius:7px;background:#efffe4;color:#244413}.tc-lorn-banner b{font-weight:750}.tc-lorn-label{display:inline-block;margin-bottom:5px;padding:3px 8px;border-radius:999px;background:#9cff57;color:#173600;font-weight:750;font-size:11px}.tc-toggle-note{font-size:11px;color:#5c6877}`;document.documentElement.appendChild(style);}
async function load(){const u=n=>chrome.runtime.getURL('generated/'+n);const stored=await chrome.storage.local.get({[STORAGE_KEY]:false});lornGreen=Boolean(stored[STORAGE_KEY]);const remote=await chrome.storage.local.get(['taxacheckRemoteNames','taxacheckRemoteEpithets']);if(remote.taxacheckRemoteNames&&remote.taxacheckRemoteEpithets){names=remote.taxacheckRemoteNames;epithets=remote.taxacheckRemoteEpithets;}else{[names,epithets]=await Promise.all([fetch(u('names.json')).then(r=>r.json()),fetch(u('epithets.json')).then(r=>r.json())]);}}
function monomial(x){return Array.isArray(x?.rank)&&x.rank.some(r=>MONO_RANKS.has(String(r).toLowerCase()));}
function lornHistories(x){return (x?.history||[]).filter(r=>r.source==='LPSN'&&LORN_STATUS.test(String(r.status||'')));}
function displacedLoRN(x){return lornHistories(x).find(r=>LORN_DISPLACED.test(String(r.status||'')));}
function isLoRN(x){return lornHistories(x).length>0||Boolean(x?.lorn_medically_relevant)||(Array.isArray(x?.lorn_descendants)&&x.lorn_descendants.length>0);}
function recommendedLoRNName(x){if(Array.isArray(x?.lorn_descendants)&&x.lorn_descendants.length){const genera=[...new Set(x.lorn_descendants.map(d=>d.recommended_genus).filter(Boolean))];return genera.length?genera.join(', '):x.name;}const histories=lornHistories(x);const displaced=histories.find(r=>LORN_DISPLACED.test(String(r.status||'')));if(displaced?.correct_name)return displaced.correct_name;const explicitlyRecommended=histories.find(r=>/recommended\s+for\s+(?:human\s+or\s+veterinary\s+)?medical\s+use/i.test(String(r.status||''))&&!/not\s+recommended/i.test(String(r.status||'')));return explicitlyRecommended?.correct_name||explicitlyRecommended?.display_name||x?.name||'';}
function visualState(x){if(lornGreen&&isLoRN(x))return'lorn-green';if(displacedLoRN(x))return'lpsn';return x.state;}
function applyVisualClass(span){if(!span?.__tc)return;for(const cls of [...span.classList])if(cls.startsWith('tc-')&&cls!=='tc-hit')span.classList.remove(cls);span.classList.add('tc-'+visualState(span.__tc));}
function refreshVisuals(){document.querySelectorAll('.tc-hit').forEach(applyVisualClass);}
function find(t){const out=[];let m;FULL.lastIndex=0;while((m=FULL.exec(t))){if(commonFirstWord(m[1])||BLOCKED.has(m[2].toLowerCase().replace(/\.$/,'')))continue;const k=m[0].toLowerCase(),x=names[k],ks=epithets[m[2].toLowerCase()]||[];if(x)out.push({s:m.index,e:m.index+m[0].length,x});else if(ks.length)out.push({s:m.index,e:m.index+m[0].length,x:{name:m[0],state:'ambiguous',candidate_keys:ks}});}ABBR.lastIndex=0;while((m=ABBR.exec(t))){if(BLOCKED.has(m[2].toLowerCase().replace(/\.$/,''))||out.some(a=>m.index<a.e&&m.index+m[0].length>a.s))continue;const initial=m[1].toLowerCase(),allKs=epithets[m[2].toLowerCase()]||[],matchingKs=allKs.filter(k=>String(k).toLowerCase().startsWith(initial+' '));if(matchingKs.length===1)out.push({s:m.index,e:m.index+m[0].length,x:names[matchingKs[0]]});else if(matchingKs.length>1)out.push({s:m.index,e:m.index+m[0].length,x:{name:m[0],state:'ambiguous',candidate_keys:matchingKs,abbreviation:true}});else if(allKs.length)out.push({s:m.index,e:m.index+m[0].length,x:{name:m[0],state:'ambiguous',candidate_keys:allKs,abbreviation:true,initial_mismatch:true,written_initial:m[1],epithet:m[2]}});}MONO.lastIndex=0;while((m=MONO.exec(t))){if(out.some(a=>m.index<a.e&&m.index+m[0].length>a.s))continue;const x=names[m[0].toLowerCase()];if(x&&monomial(x))out.push({s:m.index,e:m.index+m[0].length,x});}return out.sort((a,b)=>a.s-b.s||b.e-a.e).filter((x,i,a)=>!i||x.s>=a[i-1].e);}
function scanNode(n){if(!n.nodeValue?.trim()||!n.parentElement||n.parentElement.closest(SKIP))return;const t=n.nodeValue,h=find(t);if(!h.length)return;const f=document.createDocumentFragment();let c=0;for(const q of h){f.append(t.slice(c,q.s));const s=document.createElement('span');s.className='tc-hit';s.textContent=t.slice(q.s,q.e);s.__tc=q.x;applyVisualClass(s);f.append(s);c=q.e;}f.append(t.slice(c));n.replaceWith(f);}
function scan(root=document){const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),a=[];while(w.nextNode())a.push(w.currentNode);a.forEach(scanNode);}
function scanStructuredNames(root=document){const headings=root.querySelectorAll?.('h1,h2,h3,h4,[role="heading"]')||[];for(const heading of headings){if(heading.closest(SKIP)||heading.dataset.tcStructured==='1')continue;const fullText=heading.textContent||'';let match;const regex=/\b([A-Z][a-z-]{2,})\s+([a-z][a-z-]{1,})\b/g;while((match=regex.exec(fullText))){if(commonFirstWord(match[1]))continue;const record=names[match[0].toLowerCase()];if(!record)continue;const nodes=[],walker=document.createTreeWalker(heading,NodeFilter.SHOW_TEXT);let offset=0;while(walker.nextNode()){const node=walker.currentNode;nodes.push({node,start:offset,end:offset+node.nodeValue.length});offset+=node.nodeValue.length;}const start=match.index,end=start+match[0].length;for(const part of nodes.slice().reverse()){const a=Math.max(start,part.start),b=Math.min(end,part.end);if(a>=b)continue;const holder=part.node.parentElement?.closest('.tc-hit');if(holder){holder.__tc=record;applyVisualClass(holder);continue;}const localA=a-part.start,localB=b-part.start,text=part.node.nodeValue,fragment=document.createDocumentFragment();fragment.append(text.slice(0,localA));const span=document.createElement('span');span.className='tc-hit';span.textContent=text.slice(localA,localB);span.__tc=record;applyVisualClass(span);fragment.append(span);fragment.append(text.slice(localB));part.node.replaceWith(fragment);}}heading.dataset.tcStructured='1';}}
function lineage(r){const c=r.classification;if(!Array.isArray(c)||!c.length)return'';return c.map(x=>esc(typeof x==='string'?x:(x.name||x.full_name||''))).filter(Boolean).join(' › ');}
function sourceMarkup(r){const code=r.source==='SeqCode Registry'?'SeqCode':'ICNP',label=r.source==='SeqCode Registry'?'SeqCode Registry':'LPSN',url=String(r.source_url||'');return `${esc(code)} · ${url?`<a class="tc-source-link" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`:esc(label)}`;}
function ordinaryHeading(x){return x.state==='conflict'?'Conflicting treatments':x.state==='ambiguous'?'Manual evaluation required':x.state==='superseded'?'Superseded or redirected in at least one source':x.state==='both'?'Recognized under ICNP and SeqCode':x.state==='seqcode'?'SeqCode Registry name':x.state==='seqcode-unverified'?'SeqCode Registry entry; validity unavailable':'LPSN name';}
function show(el,e){tip?.remove();const x=el.__tc,displaced=displacedLoRN(x),recommended=recommendedLoRNName(x),lorn=isLoRN(x);tip=document.createElement('div');tip.id='tc-tip';const heading=displaced?'Taxonomically suspended due to a previous name being recommended for medical use (LoRN), while this name may better represent accurate taxonomic placement.':ordinaryHeading(x);let h=`<div class="title">${esc(x.name)}</div>`;
if(lornGreen&&lorn){const genusOnly=Boolean(x.lorn_medically_relevant)&&!lornHistories(x).length;h+=`<div class="tc-lorn-label">LoRN highlighted</div><div class="tc-lorn-banner">${genusOnly?`<b>Medically relevant LoRN-associated genus</b><br>This genus contains LoRN-associated names that use a less familiar medical classification.${recommended?`<br><b>Recommended medical genus name(s):</b> <i>${esc(recommended)}</i>`:''}`:`<b>LoRN recommended name:</b> <i>${esc(recommended||x.name)}</i>`}</div>`;}
h+=`<div class="flag">${heading}</div>`;
if(displaced){h+=`<div class="taxonomy"><b>Taxonomically suspended due to medical use, not taxonomic accuracy.</b><br>This LPSN name is not recommended for medical use under LoRN.${recommended?`<br><b>LoRN recommended name:</b> <i>${esc(recommended)}</i>`:''}<br>The recommendation reflects medical-use considerations and practical name stability, not greater taxonomic accuracy.</div>`;}
if(x.candidate_keys){if(x.initial_mismatch)h+=`<div class="taxonomy"><b>Ambiguous abbreviation:</b> no genus beginning with <i>${esc(x.written_initial)}.</i> was found for the epithet <i>${esc(x.epithet)}</i>. The names below share the epithet but do not match the written genus initial.</div>`;h+=`<div>Possible written names:</div><ul>${x.candidate_keys.map(k=>`<li><i>${esc(names[k]?.name||k)}</i></li>`).join('')}</ul>`;}else for(const r of x.history||[]){const recordDisplaced=r.source==='LPSN'&&LORN_DISPLACED.test(String(r.status||''));h+=`<div class="source">${sourceMarkup(r)}</div><div>Rank: ${esc(r.rank||'not supplied')}</div><div>Status: ${esc(r.status||'not supplied')}</div>${recordDisplaced&&r.correct_name?`<div><b>LoRN recommended name:</b> <i>${esc(r.correct_name)}</i></div>`:r.superseded?`<div><b>Correct name:</b> ${r.correct_name?`<i>${esc(r.correct_name)}</i>`:'not resolved in the downloaded source data'}</div>`:''}${r.source!=='SeqCode Registry'?`<div>Validly published: ${esc(r.validly_published===''?'not supplied':r.validly_published)}</div>`:''}${lineage(r)?`<div class="taxonomy">${lineage(r)}</div>`:''}`;}
tip.innerHTML=h;document.documentElement.append(tip);move(e);}
function move(e){if(!tip)return;const r=tip.getBoundingClientRect();tip.style.left=Math.max(8,Math.min(innerWidth-r.width-8,e.clientX+12))+'px';tip.style.top=Math.max(8,Math.min(innerHeight-r.height-8,e.clientY+12))+'px';}
installStyles();load().then(()=>{scan();scanStructuredNames();new MutationObserver(ms=>ms.forEach(m=>m.addedNodes.forEach(n=>n.nodeType===3?scanNode(n):n.nodeType===1&&!n.closest?.('.tc-hit')&&(scan(n),scanStructuredNames(n.parentElement||document))))).observe(document.documentElement,{subtree:true,childList:true,characterData:true});chrome.storage.onChanged.addListener((changes,area)=>{if(area==='local'&&changes[STORAGE_KEY]){lornGreen=Boolean(changes[STORAGE_KEY].newValue);refreshVisuals();tip?.remove();tip=null;}});document.addEventListener('mouseover',e=>{const x=e.target.closest?.('.tc-hit');if(x)show(x,e);});document.addEventListener('mousemove',move,{passive:true});document.addEventListener('mouseout',e=>{if(e.target.closest?.('.tc-hit')&&!e.relatedTarget?.closest?.('#tc-tip')){tip?.remove();tip=null;}});}).catch(console.error);

/* tcReliabilitySweep: virtualized editors and late-rendered webpage content */
const tcReliabilityState={timer:null,last:0,busy:false};
function tcUsableText(node){if(!node||node.nodeType!==Node.TEXT_NODE||!node.nodeValue?.trim()||!node.parentElement)return false;return !node.parentElement.closest('script,style,noscript,textarea,input,select,option,code,pre,svg,canvas,.tc-hit,#tc-tip');}
function tcScanSubtree(root){if(!root)return;if(root.nodeType===Node.TEXT_NODE){if(tcUsableText(root))scanNode(root);return;}if(![Node.ELEMENT_NODE,Node.DOCUMENT_NODE,Node.DOCUMENT_FRAGMENT_NODE].includes(root.nodeType))return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode:n=>tcUsableText(n)?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT}),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(scanNode);}
function tcTextParts(block){const walker=document.createTreeWalker(block,NodeFilter.SHOW_TEXT,{acceptNode:n=>tcUsableText(n)||n.parentElement?.closest('.tc-hit')?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT}),parts=[];let offset=0;while(walker.nextNode()){const node=walker.currentNode;parts.push({node,start:offset,end:offset+node.nodeValue.length});offset+=node.nodeValue.length;}return parts;}
function tcWrapPart(part,start,end,record){const a=start-part.start,b=end-part.start;if(a>=b)return;const holder=part.node.parentElement?.closest('.tc-hit');if(holder){holder.__tc=record;applyVisualClass(holder);return;}const value=part.node.nodeValue,f=document.createDocumentFragment();f.append(value.slice(0,a));const span=document.createElement('span');span.className='tc-hit';span.textContent=value.slice(a,b);span.__tc=record;applyVisualClass(span);f.append(span);f.append(value.slice(b));part.node.replaceWith(f);}
function tcReconcileBlock(block){if(!block||block.closest?.('#tc-tip')||block.dataset.tcReliable==='1')return;block.dataset.tcReliable='1';try{const parts=tcTextParts(block);if(!parts.length)return;const text=parts.map(p=>p.node.nodeValue).join(''),regex=/\\b([A-Z][a-z-]{2,})[\\s\\u00a0\\u2009\\u202f]+([a-z][a-z-]{1,})\\b/g,matches=[];let m;while((m=regex.exec(text))){if(commonFirstWord(m[1]))continue;const record=names[(m[1]+' '+m[2]).toLowerCase()];if(record&&Array.isArray(record.rank)&&record.rank.some(r=>['species','subspecies','variety','form'].includes(String(r).toLowerCase())))matches.push({start:m.index,end:m.index+m[0].length,record});}for(const hit of matches.reverse())for(const part of parts.slice().reverse()){const a=Math.max(hit.start,part.start),b=Math.min(hit.end,part.end);if(a<b)tcWrapPart(part,a,b,hit.record);}}finally{delete block.dataset.tcReliable;}}
function tcVisibleBlocks(){const selector='p,li,dd,dt,td,th,figcaption,h1,h2,h3,h4,h5,h6,[role="heading"],[role="paragraph"],[contenteditable="true"]';return [...document.querySelectorAll(selector)].filter(el=>{if(el.closest('#tc-tip'))return false;const r=el.getBoundingClientRect();return r.width>0&&r.height>0&&r.bottom>-300&&r.top<innerHeight+300;});}
function tcShadowSweep(root=document){for(const el of root.querySelectorAll?.('*')||[])if(el.shadowRoot){tcScanSubtree(el.shadowRoot);tcShadowSweep(el.shadowRoot);}}
function tcReliabilitySweep(force=false){const now=Date.now();if(tcReliabilityState.busy||(!force&&now-tcReliabilityState.last<650))return;tcReliabilityState.busy=true;tcReliabilityState.last=now;try{tcScanSubtree(document);for(const block of tcVisibleBlocks())tcReconcileBlock(block);tcShadowSweep();refreshVisuals();}finally{tcReliabilityState.busy=false;}}
function tcQueueSweep(delay=60){clearTimeout(tcReliabilityState.timer);tcReliabilityState.timer=setTimeout(()=>tcReliabilitySweep(true),delay);}
const tcObserver=new MutationObserver(mutations=>{for(const mutation of mutations){if(mutation.type==='characterData'&&tcUsableText(mutation.target))scanNode(mutation.target);for(const node of mutation.addedNodes)tcScanSubtree(node);}tcQueueSweep(40);});
tcObserver.observe(document.documentElement,{subtree:true,childList:true,characterData:true});
document.addEventListener('input',()=>tcQueueSweep(80),true);document.addEventListener('keyup',()=>tcQueueSweep(90),true);document.addEventListener('selectionchange',()=>tcQueueSweep(100));document.addEventListener('click',()=>tcQueueSweep(120),true);document.addEventListener('scroll',()=>tcQueueSweep(80),{passive:true,capture:true});document.addEventListener('visibilitychange',()=>{if(!document.hidden)tcReliabilitySweep(true);});window.addEventListener('focus',()=>tcReliabilitySweep(true));setInterval(()=>{if(!document.hidden)tcReliabilitySweep(false);},1500);setTimeout(()=>tcReliabilitySweep(true),250);
})();
